- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create directory for SSL certs
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: "0755"

- name: Generate self-signed SSL certificate
  command: >
    openssl req -x509 -nodes -days 365
    -newkey rsa:2048
    -keyout /etc/nginx/ssl/petclinic.key
    -out /etc/nginx/ssl/petclinic.crt
    -subj "/CN={{ nginx_server_name }}"
  args:
    creates: /etc/nginx/ssl/petclinic.crt

- name: Copy NGINX reverse proxy config for Petclinic
  template:
    src: petclinic.conf.j2
    dest: /etc/nginx/sites-available/petclinic
    mode: "0644"
  notify: restart nginx

- name: Enable Petclinic site (symlink)
  file:
    src: /etc/nginx/sites-available/petclinic
    dest: /etc/nginx/sites-enabled/petclinic
    state: link
    force: yes
  notify: restart nginx

- name: Remove default NGINX site (optional)
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Add moja-klinika.local to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ nginx_server_name }}"
    state: present
  when: nginx_server_name is defined
  notify: restart nginx
