---
- name: Create Prometheus user
  user:
    name: promusr
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: Download Prometheus archive
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Create Prometheus data directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: promusr
    group: promusr

- name: Create Prometheus config directory
  file:
    path: /etc/prometheus
    state: directory
    owner: promusr
    group: promusr

- name: Copy Prometheus config file from template
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: promusr
    group: promusr
    mode: "0644"

- name: Create symlink to Prometheus binary
  file:
    src: /opt/prometheus-2.52.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    state: link
    force: yes

- name: Create systemd service file for Prometheus
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus Monitoring
      After=network.target

      [Service]
      User=promusr
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus \
        --web.listen-address=0.0.0.0:9090

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start Prometheus
  systemd:
    daemon_reload: yes
    name: prometheus
    enabled: yes
    state: restarted
